deploy:
  needs: test

  permission:
    contents: write
    pages: write
    id-token: write

  environment:
    name: production
    url: ${{ steps.deployment.outputs.page_url }}

  runs-on: ubuntu-latest

  steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: configure github pages
      uses: actions/configure-pages@v3
      with:
        static_site_generator: next

    - run: npm install
    - run: npm run build

    - name: upload artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./out"

    - name: deploy
      id: deployment
      uses: actions/deploy-pages@v1
